In [55]:
import operator
import tensorflow as tf
import numpy as np
#sve transponirano drugacije, mozda greska u backpropu kod self.W azuriranja.. i suma biasa... 

In [2]:
np.dot(np.array([[[1,2],[3,4]],[[3,4],[3,4]]]),np.array([[1,2],[2,3]]))

array([[[ 5,  8],
        [11, 18]],

       [[11, 18],
        [11, 18]]])

In [3]:
minibatch_size = 3
softmax_o = np.array([[0.2,0.3,0.5],[0.5,0.3,0.2],[0.3,0.2,0.5]])
byz = np.array([[0,1,2],[1,1,1],[0,0,0]])
loss2 = -np.log(softmax_o[range(minibatch_size),byz[range(minibatch_size),2]])
print softmax_o[range(minibatch_size),byz[range(minibatch_size),2]]
print byz[range(minibatch_size),2]
loss2s = np.sum(loss2)/minibatch_size
print loss2, loss2s
print -np.log(0.5)

[ 0.5  0.3  0.3]
[2 1 0]
[ 0.69314718  1.2039728   1.2039728 ] 1.0336975964
0.69314718056


# Dataset modul valjda...

In [4]:
zip(['a','b','c'], range(3))
temp_b = np.random.randint(2,size=(1,2))
temp = np.random.randint(3,size=(4,2))
print temp_b
print temp
print temp + temp_b
print np.sum(temp,1)
for i in reversed(range(5)):
    print i

test = np.random.randint(4,size=(3,3))
print test
print
print test[:,1]

t1 = np.random.randint(4,size=(2,2))
t2 = np.random.randint(4,size=(2,2))
t3 = np.random.randint(4,size=(2,2))
tem = []
tem.append(t1)
tem.append(t2)
tem.append(t3)
print np.array(tem).shape

[[1 1]]
[[2 0]
 [1 1]
 [2 0]
 [1 1]]
[[3 1]
 [2 2]
 [3 1]
 [2 2]]
[2 2 2 2]
4
3
2
1
0
[[0 1 2]
 [1 0 3]
 [3 1 1]]

[1 0 1]
(3, 2, 2)


In [59]:
# data = "testfile\n1234\nabcttt"
# dictionary ={}
# for letter in data:
#     if letter in dictionary:
#         dictionary[letter] += 1
#     else:
#         dictionary[letter] = 1
# sorted_x = sorted(dictionary.items(), key=operator.itemgetter(1),reverse=True)
# print sorted_x
# print map(lambda x: x[0],sorted_x)

D = Dataset(2,4)
D.preprocess("untitled.txt")
print D.sorted_chars
print
print D.char2id
print
print D.id2char
print
print D.x
print
print D.encode('test')
print
print D.decode([0,0,1,1])
print
print "minibatch"
print D.create_minibatches()
print
print D.next_minibatch()
print
print D.next_minibatch()
print
print D.next_minibatch()
print
print D.next_minibatch()
print
test2 = D.next_minibatch()
print "test", test2
print test2[0]
print test2[1][:,2]
print test2[2]

[u't', u'e', u'\n', u'a', u'c', u'b', u'f', u'i', u'l', u'3', u'1', u's', u'2', u'4']

{u'a': 3, u'c': 4, u'b': 5, u'e': 1, u'f': 6, u'i': 7, u's': 11, u'\n': 2, u'l': 8, u'1': 10, u'3': 9, u'2': 12, u't': 0, u'4': 13}

{0: u't', 1: u'e', 2: u'\n', 3: u'a', 4: u'c', 5: u'b', 6: u'f', 7: u'i', 8: u'l', 9: u'3', 10: u'1', 11: u's', 12: u'2', 13: u'4'}

[ 0  1 11  0  6  7  8  1  2 10 12  9 13  2  3  5  4  0  0  0]

[ 0  1 11  0]

[u't' u't' u'e' u'e']

minibatch
None

(False, array([[ 0,  1, 11,  0],
       [ 2, 10, 12,  9]]), array([[ 1, 11,  0,  6],
       [10, 12,  9, 13]]))

(False, array([[ 6,  7,  8,  1],
       [13,  2,  3,  5]]), array([[7, 8, 1, 2],
       [2, 3, 5, 4]]))

(True, array([[ 0,  1, 11,  0],
       [ 2, 10, 12,  9]]), array([[ 1, 11,  0,  6],
       [10, 12,  9, 13]]))

(False, array([[ 6,  7,  8,  1],
       [13,  2,  3,  5]]), array([[7, 8, 1, 2],
       [2, 3, 5, 4]]))

test (True, array([[ 0,  1, 11,  0],
       [ 2, 10, 12,  9]]), array([[ 1, 11,  0,  6],
      

In [7]:
dytest = np.random.randint(4,size=(3,2)) #minibatch x voc
hiddentest = np.random.randint(4,size=(3,4)) #minibatch x hidden
print np.dot(dytest.transpose(),hiddentest)
print np.dot(hiddentest.transpose(),dytest)
print np.dot(np.array([1,2]),np.array([[2,3],[4,5]]))

[[10 12 12  8]
 [ 3  3  3  3]]
[[10  3]
 [12  3]
 [12  3]
 [ 8  3]]
[10 13]


In [58]:
class Dataset():
    # ...
    # Code is nested in class definition, indentation is not representative.
    # "np" stands for numpy.
    def __init__(self, batch_size, sequence_length):
        self.batch_size = batch_size
        self.sequence_length = sequence_length
        self.batch_pointer = 0
        
    def preprocess(self, input_file):
        with open(input_file, "r") as f:
            data = f.read().decode("utf-8")

        # count and sort most frequent characters
        
        dictionary ={}
        for letter in data:
            if letter in dictionary:
                dictionary[letter] += 1
            else:
                dictionary[letter] = 1
        sorted_x = sorted(dictionary.items(), key=operator.itemgetter(1),reverse=True)
        self.sorted_chars = map(lambda x: x[0],sorted_x)
        
        # self.sorted chars contains just the characters ordered descending by frequency
        self.char2id = dict(zip(self.sorted_chars, range(len(self.sorted_chars)))) 
        # reverse the mapping
        self.id2char = {k:v for v,k in self.char2id.items()}
        # convert the data to ids
        self.x = np.array(map(self.char2id.get, data))

    def encode(self, sequence):
        # returns the sequence encoded as integers
        return np.array(map(self.char2id.get, sequence))

    def decode(self, encoded_sequence):
        # returns the sequence decoded as letters
        return np.array(map(self.id2char.get, encoded_sequence))

    # ...
    
    # ...
    # Code is nested in class definition, indentation is not representative.

    def create_minibatches(self):
        self.num_batches = int(len(self.x) / (self.batch_size * self.sequence_length)) # calculate the number of batches
        # Is all the data going to be present in the batches? Why?
        # What happens if we select a batch size and sequence length larger than the length of the data?

        #######################################
        #       Convert data to batches       #
        #######################################
        if len(self.x) < self.sequence_length+1:
            raise Exception("Nedovoljno podataka za jednu kombinaciju ulaza/izlaza sa zadanim sequence lengthom")
            
        if self.num_batches == 0:
            raise Exception("Nemoguce napraviti niti jedan batch sa zadanim parametrima")
            
        temp_inp_out_combinations = []    
        for i in range(self.num_batches*self.batch_size): #kreiram sve kombinacije ulaz-izlaz pa cu ih kasnije spajat
            inputs = np.array([elem for elem in self.x[(i)*self.sequence_length:(i+1)*self.sequence_length]])
            targets = np.array([elem for elem in self.x[(i)*self.sequence_length+1:(i+1)*self.sequence_length+1]])
            temp_inp_out_combinations.append((inputs,targets))
            
        self.batches = []
        num_ins = len(temp_inp_out_combinations)
        for i in range(num_ins):
            inp, out = temp_inp_out_combinations[i]
            if i < self.num_batches:
                batch_x = []
                batch_y = []
                self.batches.append([])
            else:
                batch_x, batch_y = self.batches[i%self.num_batches]
            batch_x.append(inp)
            batch_y.append(out)
            self.batches[i%self.num_batches] = (batch_x,batch_y)
            
        for i in range(self.num_batches):
                batch_x, batch_y = self.batches[i]
                self.batches[i] = (np.array(batch_x),np.array(batch_y))
#         cnt = 0
        
#         for j in range(self.num_batches):
#             batch = []
#             batch_x = []
#             batch_y = []
#             for i in range(self.batch_size):
#                 inputs = np.array([elem for elem in self.x[(cnt)*self.sequence_length:(cnt+1)*self.sequence_length]])
#                 targets = np.array([elem for elem in self.x[(cnt)*self.sequence_length+1:(cnt+1)*self.sequence_length+1]])
#                 batch_x.append(inputs)
#                 batch_y.append(targets)
#                 batch.append((inputs,targets))
#                 cnt +=1
#             self.batches.append((np.array(batch_x), np.array(batch_y)))
            
    
    # ...
    # Code is nested in class definition, indentation is not representative.
    def next_minibatch(self):
        # ...
        new_epoch = False
        if self.batch_pointer >= self.num_batches:
            self.batch_pointer = 0
            new_epoch = True
            
        batch_x, batch_y = self.batches[self.batch_pointer]
        self.batch_pointer += 1
        # handling batch pointer & reset
        # new_epoch is a boolean indicating if the batch pointer was reset
        # in this function call
        return new_epoch, batch_x, batch_y

# RNN dio...

In [60]:
class RNN():
    # ...
    # Code is nested in class definition, indentation is not representative.
    # "np" stands for numpy
    def __init__(self, hidden_size, sequence_length, vocab_size, learning_rate):
        self.hidden_size = hidden_size
        self.sequence_length = sequence_length
        self.vocab_size = vocab_size
        self.learning_rate = learning_rate

        self.U = np.random.normal(0, 1e-2,(vocab_size,hidden_size))# ... input projection
        self.W = np.random.normal(0, 1e-2,(hidden_size, hidden_size)) # ... hidden-to-hidden projection
        self.b = np.random.normal(0, 1e-2,(1, hidden_size)) # ... input bias
        
        self.V = np.random.normal(0, 1e-2,(hidden_size,vocab_size)) # ... output projection
        self.c = np.random.normal(0, 1e-2,(1,vocab_size)) # ... output bias

        # memory of past gradients - rolling sum of squares for Adagrad
        self.memory_U, self.memory_W, self.memory_V = np.zeros_like(self.U), np.zeros_like(self.W), np.zeros_like(self.V)
        self.memory_b, self.memory_c = np.zeros_like(self.b), np.zeros_like(self.c)
        
        
    def encode_1_of_k_rep(self, encoded_sequence): #encodes array of integers for a batch to 1-of-k representation
        minibatches = encoded_sequence.shape[0]
        new_sequence = np.zeros((minibatches, self.vocab_size)) # encode in 1-of-k representation
        new_sequence[range(minibatches),encoded_sequence.astype(np.int32)] = 1
        return new_sequence.astype(np.int32)
        
    # ...
    # Code is nested in class definition, indentation is not representative.
    def rnn_step_forward(self, x, h_prev):
        #x - minibatch x vocab
        #h_prev - minibatch x hidden size

        cache = {}
        hidden_state = np.tanh(np.dot(x, self.U) + np.dot(h_prev,self.W) + self.b) #minibatch x hidden
        output = np.dot(hidden_state, self.V) + self.c #minibatch x vocab_size
        soft_sum = np.sum(np.exp(output),1)
        softmax_output = np.exp(output)/(soft_sum[:,None]) #minibatch x vocab_size
        
        cache["input"] = x
        cache["hprev"] = h_prev
        cache["hstate"] = hidden_state
        cache["output"] = output
        cache["softmax_out"] = softmax_output
        
        return hidden_state.copy(), cache


    def rnn_forward(self, x, h0):
        
        #x je meni shape minibatch size x sequence_length x 1 gdje je 1 zapravo integer reprezentacija charactera
        #koju encodiram prije predaje funkciji
        h, cache = {}, {}
        h[-1] = h0
        hprev = h0
        minibatches, seq_length = x.shape
        for i in range(self.sequence_length):
            current_timestep_inputs = x[range(minibatches),i]
            current_timestep_inputs_encoded = self.encode_1_of_k_rep(current_timestep_inputs) # minibatch x vocab_size
            new_hidden, new_cache = self.rnn_step_forward(current_timestep_inputs_encoded, hprev)
            hprev = new_hidden
            cache[i] = new_cache
            h[i]= new_hidden.copy()
        # return the hidden states for the whole time series (T+1) and a tuple of values needed for the backward step

        return h, cache
    
    def rnn_BPTT(self, batch_x, batch_y, cache_dict, h0):
        #konvencija imenovanja derivacija je W tezine a mali znakovi # -> # odnosno matrica koja preslikava hidden u hidden je hh
        # input u hidden je xh , hidden u output hy, a ovo self.U ostaje jer je takav template iz zadatka :S sredim kasnije... valjda
        
        dWxh, dWhh, dWhy = np.zeros_like(self.U), np.zeros_like(self.W), np.zeros_like(self.V)
        dbh, dby = np.zeros_like(self.b), np.zeros_like(self.c)
        dhnext = np.zeros_like(h0) #minibatch x hidden_size
        minibatch_size = h0.shape[0]
        loss = 0
        cache_length = len(cache_dict.keys())
        for i in reversed(range(cache_length)):
            ## compute derivative of error w.r.t the output probabilites
            ## dE/dy[j] = y[j] - t[j]
            
            x_input = cache_dict[i]["input"]
            h_prev = cache_dict[i]["hprev"] #minibatch x hidden
            hidden_state = cache_dict[i]["hstate"] #minibatch x hidden_size
            output = cache_dict[i]["output"]
            softmax_output =cache_dict[i]["softmax_out"] #minibatch x vocab
            
            dy = np.copy(softmax_output)
            dy[range(minibatch_size),batch_y[range(minibatch_size),i]] -= 1 # backprop into y, size = minibatch x vocab_size

            ## output layer doesnot use activation function, so no need to compute the derivative of error with regard to the net input
            ## of output layer. 
            ## then, we could directly compute the derivative of error with regard to the weight between hidden layer and output layer.
            ## dE/dy[j]*dy[j]/dWhy[j,k] = dE/dy[j] * h[k]

            dWhy += np.dot(hidden_state.T, dy)
            dby += np.sum(dy,0)
            
            ## backprop into h
            ## derivative of error with regard to the output of hidden layer
            ## derivative of H, come from output layer y and also come from H(t+1), the next time H
            dh = np.dot(dy, self.V.T) + dhnext
            ## backprop through tanh nonlinearity
            ## derivative of error with regard to the input of hidden layer
            ## dtanh(x)/dx = 1 - tanh(x) * tanh(x)
            dhraw = (1 - hidden_state*hidden_state) * dh #minibatch x hidden
            dbh += np.sum(dhraw,0)

            ## derivative of the error with regard to the weight between input layer and hidden layer
            dWxh += np.dot(x_input.T,dhraw) # vocab x hidden
            dWhh += np.dot(h_prev.T, dhraw) # hidden x hidden
            ## derivative of the error with regard to H(t+1)
            ## or derivative of the error of H(t-1) with regard to H(t)
            dhnext = np.dot(dhraw, self.W) #minibatch x hidden
            
            loss += -np.log(softmax_output[range(minibatch_size),batch_y[range(minibatch_size),i]])
        
        for dparam in [dWxh, dWhh, dWhy, dbh, dby]:
            np.clip(dparam/minibatch_size, -5, 5, out=dparam) # clip to mitigate exploding gradients
            
        loss = np.sum(loss)/minibatch_size
        return loss, dWxh, dWhh, dWhy, dbh, dby, cache_dict[cache_length-1]["hstate"]
    
    def step(self, h0, batch_x, batch_y):
        hidden_dict, cache_dict = self.rnn_forward(batch_x,h0)
        loss, dU, dW, dV, db, dc, new_h0 = self.rnn_BPTT(batch_x, batch_y, cache_dict, h0)
        self.update(dU, dW, db, dV, dc)
        return loss, new_h0
    
    
    def update(self, dU, dW, db, dV, dc):

        # update memory matrices
        # perform the Adagrad update of parameters
        for param, dparam, mem in zip([self.U, self.W, self.b, self.V, self.c],
                                [dU, dW, db, dV, dc],
                                [self.memory_U, self.memory_W, self.memory_b, self.memory_V, self.memory_c]):
            mem += dparam * dparam
            ## learning_rate is adjusted by mem, if mem is getting bigger, then learning_rate will be small
            ## gradient descent of Adagrad
            param += -self.learning_rate * dparam / np.sqrt(mem + 1e-8) # adagrad update
    
    # ...
    # code not necessarily nested in class definition
    def sample(self, dataset, seed = 'HAN:\nIs that good or bad?\n\n', n_sample=300):
        hidden = np.zeros((1, self.hidden_size))
        encoded = dataset.encode(seed)
        one_hot = self.encode_1_of_k_rep(encoded)
        # inicijalizirati h0 na vektor nula
        # seed string pretvoriti u one-hot reprezentaciju ulaza
        output_string = ""
        last_output = ""
        seed_length = len(seed)
        for inp in one_hot:
            hidden, cache = self.rnn_step_forward(inp, hidden)
            output = np.random.choice(range(self.vocab_size), p=cache["softmax_out"].ravel())
            last_output = np.array([output])
            #output_string+=dataset.decode(last_output)[0]
            
        for k in range(n_sample-seed_length):
            last_output_encoded = self.encode_1_of_k_rep(last_output)
            hidden, cache = self.rnn_step_forward(last_output_encoded, hidden)
            output = np.random.choice(range(self.vocab_size), p=cache["softmax_out"].ravel())
            last_output = np.array([output])
            output_string+=dataset.decode(last_output)[0]
            
        return output_string

In [12]:
testRNN = RNN(10,50,5,0.01)
# h, cache = testRNN.rnn_forward(np.array([[1.,2.,1.]]),np.zeros((1,10)))
# for key in cache.keys():
#     #print key, cache[key]["output"], cache[key]["input"]
#     pass

inp = np.array([[1.,2.,1.,4.,3.]*10,[3.,1.,3.,2.,4.]*10])
wanted = np.array([[2,2,1,3,3]*10,[1,2,3,1,1]*10])
init_state = np.zeros((2,10))
for i in range(5000):
    loss, new_h0 = testRNN.step(init_state.astype(np.float32),inp,wanted)
    if i % 1000 == 0:
        print loss

        
h, cache = testRNN.rnn_forward(inp,init_state.astype(np.float32))
tocni, netocni = 0,0
for key in cache.keys():
    netocni_current = np.count_nonzero(np.argmax(cache[key]["output"],1)-wanted[:,key])
    tocni +=2-netocni_current
    netocni+=netocni_current
#     print key, np.argmax(cache[key]["output"][0]), wanted[0][key]
    pass

print tocni, netocni, tocni/(1.*netocni+tocni), netocni+tocni


80.4454671309


KeyboardInterrupt: 

In [61]:
# ...
# code not necessarily nested in class definition

def run_language_model(dataset, max_epochs, hidden_size=100, sequence_length=30, learning_rate=1e-1, sample_every=100):
    
    vocab_size = len(dataset.sorted_chars)
    modelRNN = RNN(hidden_size=hidden_size,sequence_length=sequence_length,learning_rate=learning_rate,vocab_size=vocab_size)

    current_epoch = 0 
    batch = 0
    num_batches = dataset.num_batches
    batch_size = dataset.batch_size

    h0 = np.zeros((batch_size, hidden_size))

    average_loss = 0

    while current_epoch < max_epochs: 
        e, x, y = dataset.next_minibatch()
        
        if e: 
            batch=0
            current_epoch += 1
            h0 = np.zeros((batch_size, hidden_size))
            # why do we reset the hidden state here?

        # One-hot transform the x and y batches
        x_oh, y_oh = None, None

        # Run the recurrent network on the current batch
        # Since we are using windows of a short length of characters,
        # the step function should return the hidden state at the end
        # of the unroll. You should then use that hidden state as the
        # input for the next minibatch. In this way, we artificially
        # preserve context between batches.
        loss, h0 = modelRNN.step(h0, x, y)

        #if batch % sample_every == 0:
        if e and current_epoch %10 == 0:
            print "Epoch %s/%s, Batch %s/%s\nCurrent batch loss = %s" % (current_epoch, max_epochs, batch, num_batches, loss)
            sampled_text = modelRNN.sample(dataset)
            print "#SAMPLED TEXT#\n%s\n####END###\n" % sampled_text
        batch += 1
        

In [38]:
D = Dataset(5,30)
D.preprocess("input.txt")
D.create_minibatches()
run_language_model(D,100,sample_every=3500)

Epoch 5/100, Batch 0/3947
Current batch loss = 70.2882316104
#SAMPLED TEXT#
ERORALA:
Is I dekn, brat Su`o a ver ssaythas lihor I faop Hut kat... yod haman.


MEA:
I'r mencere mamust of rane ip ar'tys till plentoe I'bong?

EDDFRA:
Sed!

JEY:
Ler.

DENUYZT a ton Lare's whet hacser it ay mas?

DU hat weednthe heas youe The'm to bo tre daly to by you 
####END###

Epoch 10/100, Batch 0/3947
Current batch loss = 66.4229043993
#SAMPLED TEXT#
BE:
I Bellim!

ORARA:
The shoee wekm, I'r, sht dily.

RARARARAUKE:
I to?

LEKE.

We  ISSO3DOY:
Ome don'll yacking lere wald ou.r I've cate o DOER:
We abou dre pre inch they.

PRITHLAKA:
Yow thine.
P:
Manry dod hom toRme asour oh doll, I gom.

LBANLUKAR:
Yby Fedllert'ved he
####END###

Epoch 15/100, Batch 0/3947
Current batch loss = 63.9546955538
#SAMPLED TEXT#
ARCHORE:
Whern a st.

SE:
Wellfo Je ayou ponere we vioked.

SAR.
BOE D:
Loevad.  Hrich offwe m your't shings alraiig lare be just armmy gobee himel waistidlr.

rerilers to not se?

AD:
You dis or wh

In [41]:
D = Dataset(5,30)
D.preprocess("input.txt")
D.create_minibatches()
run_language_model(D,200,sample_every=3500)

Epoch 10/200, Batch 0/3947
Current batch loss = 72.159582649
#SAMPLED TEXT#
AI CHou drerife of forn sere or to me en yousn's we it.

CHA:
Id.

EDEE:
Soust nougn, thatoonger. Hanurg to you YGOOD:
POND:
I gabec not kiog iny itbeing oul be whrver it thus to lBhe Teksea socking!.

DONIE:
Wherer. Therigh beldir if aoyick.!  hice fo!

I cad to thasen't 
####END###

Epoch 20/200, Batch 0/3947
Current batch loss = 70.6747552316
#SAMPLED TEXT#
HAN:
Bre the is you there.  I whave seugr any!  Pored mamm the  to periom 're
HEN:
Thaectsl verg tant,  it. Trat is wabre thie cren.  dewr sow, foron if a rey of as all don'r mardel hald. W... Yesty cite

VARE hatee ads right well sour if all aburnowss, ued Vall wablide.


####END###

Epoch 30/200, Batch 0/3947
Current batch loss = 68.0875230263
#SAMPLED TEXT#
RELERICK
TETA:
I'm neutryou't carupt. not mick only rame thin't the muct quet.

FUNGO:
Thowh.  You's him, puch ove?

CILEckotagr. Evebbl stted a pra live ain do.

LAVERCHICH:
Howh.

LARAN:
Ro, that 

In [44]:
D = Dataset(10,30)
D.preprocess("input.txt")
D.create_minibatches()
run_language_model(D,200,sample_every=3500)

Epoch 10/200, Batch 0/1973
Current batch loss = 103.752281838
#SAMPLED TEXT#
. rII,DsIrtet  
 rnd i

 ea o tt'oae sIEnoL Ve
 uhotAT..OoO
Ltrehfsf:Wmgtw.e?:r
lpitb
C. s yatenRediw hthAeiE
is :fmsu tkw 
rsn asarou?oodi  .eIr,WA
enf hec.niE  oh
dOdr
ruerEBspehtAoc
pk  iaoLlrI
IdeHX  le.tDvpe i  id fhyty itsau
wte.h.Ant  P
r evsUrau . alwf:Nh  LdIuerl:
####END###

Epoch 20/200, Batch 0/1973
Current batch loss = 87.3839139533
#SAMPLED TEXT#
I dv iturrrit heuul h NLto trrlo g o  RDBh o wPWEWDELDDet,icriLOo mhf.

E:


COI:
io skir k tanwANTm Iv.
L
L:
at tnisseo ve nfi.


:.

Iw h r tpeh.or tpiiglidst l ldee e rdin tfareaago ag iyl Oa.
ee hic NIo sd.
!
eyee z miyto .VAAfhuerwauinsriBEONad!.YourYnh,ris ih h.a'nee
####END###

Epoch 30/200, Batch 0/1973
Current batch loss = 84.3586118822
#SAMPLED TEXT#
AolatCDEI,V:
Ph nwde,  to eysoripr  yo l at0 yhfers me bk gho heu,enugsas wFTI  wH:
ayy.

LDI: horeas

I sninne?

H:
er ttitB 'nse'leotodyr af.e eedsr at lin o reu hore me tSBkoelr oel s.
 Iataned 

In [62]:
D = Dataset(5,30)
D.preprocess("input.txt")
D.create_minibatches()
run_language_model(D,200,sample_every=3500)

Epoch 10/200, Batch 0/3947
Current batch loss = 73.8030609792
#SAMPLED TEXT#
VDZE:
Sseelekere theryend .. Lade Ot s Ziy yorg pas, won,, med.

Rid thLitlak hls'ce uns musld shermeve. Lasonthave ot. we wtisinneiol eh ko se tpicull, here bugt,. Dal c Llbeadpret Uca urtds'reoue.. Phy ylg my the ahg nous yolivol heidurgy thiced?

as sas at tanee tin ton
####END###

Epoch 20/200, Batch 0/3947
Current batch loss = 65.7453870428
#SAMPLED TEXT#
AN:
Us themt.

AUMWINMA  WHREY:
Petshive gos.

GEN:
Whatod dipsing mume thantthis youd thoce your onisw, upesent?

STELIO:
Cat thill?

FREMZR:
UVk!

TIC:
An we whing a me. Thitt!

LADDY:
Have to dom spyte is.

LUKE:
The  you you dt an wied don't Thinkt spdic ride?

JOLEOT:
####END###

Epoch 30/200, Batch 0/3947
Current batch loss = 75.79983172
#SAMPLED TEXT#
IthoophkpgithoikitfonthiigothigvithanktigheifixhtHobigohkontixhainhixthowknthougozexefy

HAHCY:
E:
DILIA:

Y:
JD:
JY:
JHY:
JE:
JK:
FR:

Y:
PIHAH:
JCK:
Y:
H:
JY:
JH:
JY:
Z:


JUH:
Y:
JU:
JY:
JIHCHAPkg